print('Enter the first number: ')

num1 =int(input())

print('Enter the second number: ')

num2 = int(input())

print('Select the operation you want to perform')

print('1. Addition')

print('2. Subtraction')

print('3. Multiplication')

print('4. Division')

print('5. Modulus')

print('6. Floor Division') 
print('7. Exponent ')

choice = input()


if (choice == '1'):
    print(num1 + num2)

elif (choice == '2'):
    print(num1 - num2)

elif (choice == '3'):
    print(num1 * num2)

elif (choice == '4'):
    print(num1 / num2)

elif(choice == '5'):
    print(num1 % num2)

elif (choice == '6'):
    print(num1 // num2)

elif (choice == '7'):
    print(num1 ** num2)

else:
    print("Invalid Input")


